Repository celery/kombu, pull requests merged in 2018-09, with the labels that each got.

#920 added retry=True
  kombu/pidbox.py
Labels: PR Type: Bugfix

#924 Fix a deprecation warning about logger.warn()
  AUTHORS
  kombu/common.py
  kombu/connection.py
  kombu/transport/etcd.py
  kombu/transport/virtual/base.py
  t/unit/test_common.py
Labels: PR Type: Enhancement

#923 Fix infinity loop in create_loop
  kombu/asynchronous/hub.py
  t/unit/asynchronous/test_hub.py
Labels: Component: Amazon SQS Broker, PR Type: Bugfix
