Repository celery/kombu, pull requests merged in 2018-08, with the labels that each got.

#884 don't cache declaration of expiring queues
  kombu/entity.py
  t/unit/test_entity.py
Labels: PR Type: Bugfix

#850 Index in sqlalchemy transport for quick sorting
  kombu/transport/sqlalchemy/models.py
Labels: PR Type: Enhancement

#880 Add parameter timeout to retry_over_time
  kombu/connection.py
  kombu/utils/functional.py
  t/unit/utils/test_functional.py
Labels: PR Type: Enhancement

#900 Allow SimpleQueue to pass 'queue_arguments' to Queue object.
  kombu/connection.py
  kombu/simple.py
  t/unit/test_simple.py
Labels: PR Type: Enhancement

#907 Increased test coverage for connection.py
  t/unit/test_connection.py
Labels: PR Type: Enhancement

#908 Added Python 3.7 to the build matrix
  .travis.yml
  requirements/docs.txt
  requirements/test-ci.txt
  tox.ini
Labels: PR Type: Task

#910 Add support for 'rediss' scheme for secure redis connections.
  kombu/connection.py
  kombu/transport/__init__.py
  t/unit/transport/test_redis.py
Labels: Component: Redis Broker, PR Type: Enhancement
