Repository celery/kombu, pull requests merged in 2019-03, with the labels that each got.

#976 Return an empty list in AWS's _on_list_ready on a timeout response
  kombu/asynchronous/aws/connection.py
Labels: Component: Amazon SQS Broker, PR Type: Bugfix, Status: Needs Test Coverage

#1029 qpid: correctly declare support for async event loop
  kombu/transport/qpid.py
  t/unit/transport/test_qpid.py
Labels: Component: Qpid Broker, PR Type: Bugfix

#1033 Reintroduce unqiue broadcast queue name generation as optional
  kombu/common.py
  t/unit/test_common.py
Labels: Component: Entities, PR Type: Enhancement
