Repository celery/kombu, pull requests merged in 2020-11, with the labels that each got.

#1264 Reformat and improve kombu transport reference docs
  docs/reference/index.rst
  docs/reference/kombu.transport.sqlalchemy.models.rst
  docs/reference/kombu.transport.sqlalchemy.rst
  kombu/transport/SLMQ.py
  kombu/transport/SQS.py
  kombu/transport/azureservicebus.py
  kombu/transport/azurestoragequeues.py
  kombu/transport/consul.py
  kombu/transport/etcd.py
  kombu/transport/filesystem.py
  kombu/transport/memory.py
  kombu/transport/mongodb.py
  kombu/transport/pyamqp.py
  kombu/transport/pyro.py
  kombu/transport/qpid.py
  kombu/transport/redis.py
  kombu/transport/sqlalchemy/__init__.py
  kombu/transport/zookeeper.py
Labels: Component: Documentation

#1269 Add timeout to producer publish
  kombu/messaging.py
  t/unit/test_messaging.py
Labels: Component: AMQP Broker, Component: pyamqp, PR Type: Enhancement

#1277 Remove python2 compatibility code
  kombu/__init__.py
  kombu/serialization.py
  kombu/transport/virtual/base.py
  kombu/utils/functional.py
  t/unit/test_serialization.py
Labels: PR Type: Enhancement
