Repository celery/kombu, pull requests merged in 2021-04, with the labels that each got.

#1316 Use a thread-safe implementation of cached_property
  kombu/utils/objects.py
  requirements/default.txt
  t/unit/utils/test_objects.py
Labels: PR Type: Bugfix

#1324 Azure Service Bus - versatile queue names fix
  kombu/transport/azureservicebus.py
  t/unit/transport/test_azureservicebus.py
Labels: Component: Azure ServiceBus Broker, PR Type: Bugfix

#1327 Fix CI failure
  .github/workflows/ci.yaml
Labels: Category: Project Governance, PR Type: Bugfix

#1328 Add support for SQLAlchemy 1.4
  kombu/transport/sqlalchemy/models.py
Labels: Component: Unsupported Broker

#1330 Coerce seconds argument to a floating point number.
  kombu/asynchronous/timer.py
Labels: Component: Event Loop, PR Type: Bugfix

#1335 Remove unused appveyor and travis configuration files
  .travis.yml
  appveyor.yml
Labels: Category: Tests, PR Type: Cleanup

#1334 Ignore kombu.transport.librabbitmq in apicheck.
  docs/conf.py
Labels: Category: Tests

#1320 chore: Refactor code quality issues
  kombu/transport/qpid.py
  kombu/utils/compat.py
  t/unit/asynchronous/test_timer.py
  t/unit/test_clocks.py
  t/unit/transport/test_redis.py
Labels: PR Type: Cleanup
