Repository celery/kombu, pull requests merged in 2021-09, with the labels that each got.

#1381 stop mentioning librabbitmq
  README.rst
Labels: PR Type: Cleanup

#1382 drop python 3.6 from CI
  .github/workflows/ci.yaml
  tox.ini
Labels: PR Type: Enhancement, Category: Project Governance

#1386 Fix missing dependency to redis in docs requirements
  requirements/docs.txt
Labels: PR Type: Bugfix, Component: Documentation
