Repository celery/kombu, pull requests merged in 2022-01, with the labels that each got.

#1467 prevent KeyError: 'purelib'
  setup.py
Labels: PR Type: Cleanup

#790 Fix issue #789: Async http code not allowing for proxy config
  kombu/asynchronous/http/curl.py
  t/unit/asynchronous/http/test_curl.py
Labels: Component: Amazon SQS Broker

#1482 The times of retrying is not correct
  kombu/connection.py
Labels: PR Type: Bugfix

#1484 Set redelivered property for Celery with Redis
  kombu/transport/redis.py
  t/unit/transport/test_redis.py
Labels: Component: Redis Broker, PR Type: Bugfix

#1486 Some small updates
  docs/userguide/simple.rst
  kombu/asynchronous/aws/sqs/queue.py
  kombu/asynchronous/http/base.py
  kombu/asynchronous/semaphore.py
  t/unit/transport/test_qpid.py
Labels: PR Type: Cleanup

#1483 Remove use of OrderedDict in various places
  kombu/connection.py
  kombu/transport/qpid.py
  kombu/transport/virtual/base.py
  t/unit/transport/test_qpid.py
Labels: PR Type: Cleanup
