Repository celery/kombu, pull requests merged in 2022-03, with the labels that each got.

#1497 try pytest 7
  requirements/test.txt
Labels: CI

#1496 SQS: Fix message arg in backoff policy
  kombu/transport/SQS.py
Labels: Component: Amazon SQS Broker

#1489 Protect set of ready tasks by lock to avoid concurrent updates
  kombu/asynchronous/hub.py
  t/unit/asynchronous/test_hub.py
Labels: PR Type: Bugfix
