Repository celery/kombu, pull requests merged in 2022-02, with the labels that each got.

#1488 Warn about missing hostname only when default one is available
  kombu/connection.py
  t/unit/test_connection.py
Labels: PR Type: Bugfix

#1487 All supported versions of Python define __package__.
  kombu/__init__.py
Labels: PR Type: Cleanup

#1495 Added global_keyprefix support for pubsub clients
  kombu/transport/redis.py
  t/unit/transport/test_redis.py
Labels: Component: Redis Broker, Status: Needs Test Coverage, PR Type: Bugfix
