Repository celery/kombu, pull requests merged in 2023-06, with the labels that each got.

#1754 fix: allow deserializing any version of UUID
  kombu/utils/json.py
  t/unit/utils/test_json.py
Labels: Component: Serialization, PR Type: Bugfix

#1755 Reverted unwanted constraint introduced in #1629 with max_retries
  kombu/connection.py
  t/unit/test_connection.py
Labels: PR Type: Bugfix

#1758 Doc fix (hotfix for #1755)
  kombu/connection.py
Labels: Component: Documentation

#1759 [fix #1726] Use boto3 for SQS async requests
  kombu/asynchronous/aws/sqs/connection.py
  kombu/asynchronous/aws/sqs/queue.py
  kombu/transport/SQS.py
  t/unit/asynchronous/aws/sqs/test_connection.py
  t/unit/asynchronous/aws/sqs/test_queue.py
  t/unit/transport/test_SQS.py
Labels: Component: Amazon SQS Broker, PR Type: Cleanup
