Repository celery/kombu, pull requests merged in 2023-04, with the labels that each got.

#1683 use pytest-freezer
  requirements/test.txt
Labels: Category: Tests, PR Type: Cleanup

#1682 test azureservicebus pure python beta
  requirements/extras/azureservicebus.txt
Labels: Component: Azure ServiceBus Broker

#1695 Add Semgrep CI
  .github/workflows/semgrep.yml
Labels: CI

#1696 drop codecov pypi version
  requirements/test-ci.txt
Labels: CI

#1621 SQS: avoid excessive GetQueueURL calls by using cached queue url
  kombu/transport/SQS.py
  kombu/transport/virtual/base.py
  t/unit/transport/test_SQS.py
Labels: Component: Amazon SQS Broker, PR Type: Enhancement
