Repository celery/kombu, pull requests merged in 2024-10, with the labels that each got.

#2133 Removed "on push" from the linter GitHub Actions workflow
  .github/workflows/linter.yml
Labels: CI

#2129 Apply errback and callback when retry occurs
  kombu/connection.py
  t/unit/test_connection.py
Labels: Component: Connection, PR Type: Bugfix

#2128 Add native delayed delivery API to kombu
  docs/reference/index.rst
  docs/reference/kombu.transport.native_delayed_delivery.rst
  docs/userguide/examples.rst
  examples/delayed_infra.py
  kombu/asynchronous/aws/connection.py
  kombu/asynchronous/aws/sqs/connection.py
  kombu/connection.py
  kombu/transport/SQS.py
  kombu/transport/native_delayed_delivery.py
  setup.cfg
  t/unit/transport/test_SQS.py
  t/unit/transport/test_azureservicebus.py
  t/unit/transport/test_mongodb.py
  t/unit/transport/test_native_delayed_delivery.py
Labels: Component: AMQP Broker, PR Type: Enhancement

#2148 Update the transport options according to the retry policy
  kombu/messaging.py
  t/unit/test_messaging.py
Labels: PR Type: Bugfix

#2150 Prepare for (pre) release: v5.5.0rc1
  .bumpversion.cfg
  Changelog.rst
  README.rst
  docs/includes/introduction.txt
  kombu/__init__.py
Labels: Category: Packaging and Release Management

#2151 Added missing changelog highlight for Google Pub/Sub
  Changelog.rst
Labels: Component: Documentation

#2166 Added a unit test that proves timeout is used when retry policy is specified
  t/unit/test_messaging.py
Labels: Category: Tests, PR Type: Enhancement

#2165 Fix regression from #2148
  kombu/transport/sqlalchemy/__init__.py
  t/unit/transport/test_sqlalchemy.py
Labels: PR Type: Bugfix, SQLAlchemy broker

#2167 Added confirm_timeout argument to publish()
  kombu/messaging.py
  t/unit/test_messaging.py
Labels: Component: AMQP Broker, PR Type: Enhancement
